Repository hashicorp/terraform-cdk-action, pull requests merged in 2023-11, with the labels that each got.

#103 chore: fix node version used in custom workflows
  .github/workflows/upgrade-cdktf.yml
  .github/workflows/upgrade-node-manually.yml
  .github/workflows/upgrade-node.yml
  .github/workflows/upgrade-terraform.yml
  projenrc/upgrade-cdktf.ts
  projenrc/upgrade-node.ts
  projenrc/upgrade-terraform.ts
Labels: automerge, auto-approve

#102 chore(deps): upgrade dependencies
  yarn.lock
Labels: automerge, dependencies

#96 chore!: change default CDKTF version to 0.19.1
  .projenrc.ts
  README.md
  action.yml
Labels: automerge, dependencies, do-not-merge

#110 chore(deps): upgrade actions/github-script & remove node-fetch
  .github/workflows/auto-approve.yml
  .github/workflows/automerge.yml
  .github/workflows/build.yml
  .github/workflows/git-tags.yml
  .github/workflows/lock.yml
  .github/workflows/pull-request-lint.yml
  .github/workflows/release.yml
  .github/workflows/upgrade-cdktf.yml
  .github/workflows/upgrade-main.yml
  .github/workflows/upgrade-node-manually.yml
  .github/workflows/upgrade-node.yml
  .github/workflows/upgrade-terraform.yml
  .projen/deps.json
  .projenrc.ts
  package.json
  scripts/check-node-versions.js
  scripts/check-terraform-version.js
  yarn.lock
Labels: auto-approve

#111 chore(deps): manage test-stacks through Dependabot
  .github/dependabot.yml
Labels: automerge, auto-approve

#113 chore: improve workflows related to testing and Dependabot
  .github/workflows/auto-approve.yml
  .github/workflows/automerge.yml
  .github/workflows/integration-tests.yml
  .github/workflows/release.yml
  .npmignore
  .projen/deps.json
  .projenrc.ts
  package.json
  projenrc/auto-approve.ts
  projenrc/automerge.ts
  scripts/update-node.sh
  test-stacks/package-lock.json
  test-stacks/package.json
  test-stacks/yarn.lock
  yarn.lock
Labels: automerge, auto-approve

#114 chore(deps): upgrade typescript & jest
  .projen/deps.json
  .projen/tasks.json
  dist/index.js
  dist/index.js.map
  package.json
  yarn.lock
Labels: automerge, dependencies, auto-approve

#115 chore(deps): upgrade dependencies
  dist/index.js
  dist/index.js.map
  dist/licenses.txt
  package.json
  yarn.lock
Labels: automerge, auto-approve

#117 chore(ci): improve auto-upgrade automations
  .github/workflows/upgrade-cdktf.yml
  .github/workflows/upgrade-node-manually.yml
  .github/workflows/upgrade-node.yml
  .github/workflows/upgrade-terraform.yml
  README.md
  projenrc/upgrade-cdktf.ts
  projenrc/upgrade-node.ts
  projenrc/upgrade-terraform.ts
Labels: automerge, auto-approve
