Repository hashicorp/terraform-cdk-action, pull requests merged in 2023-09, with the labels that each got.

#59 chore: support git version aliases
  .gitattributes
  .github/workflows/git-tags.yml
  .gitignore
  .projen/files.json
  .projenrc.ts
  projenrc/update-tags.ts
Labels: stale

#67 chore(deps): upgrade dependencies
  .projen/tasks.json
  package.json
  yarn.lock
Labels: automerge, dependencies

#69 chore: add PR template
  .github/CONTRIBUTING.md
  .github/pull_request_template.md
Labels: auto-approve

#70 chore: have GitHub releases use the Projen token
  .github/workflows/release.yml
  .projenrc.ts
Labels: auto-approve

#71 chore: fix broken git-tags workflow
  .github/workflows/git-tags.yml
  projenrc/update-tags.ts
Labels: auto-approve

#55 chore: automate updating the README
  .projen/deps.json
  .projen/tasks.json
  .projenrc.ts
  README.md
  action.yml
  dist/index.js
  dist/index.js.map
  package.json
  src/inputs.ts
  yarn.lock
Labels: auto-approve

#72 chore: fix broken git-tags workflow for real this time
  .github/workflows/git-tags.yml
  projenrc/update-tags.ts
Labels: auto-approve

#73 chore: (semi)automate upgrading Node.js
  .gitattributes
  .github/workflows/upgrade-node.yml
  .gitignore
  .projen/deps.json
  .projen/files.json
  .projenrc.ts
  dist/index.js
  dist/index.js.map
  package.json
  projenrc/upgrade-node.ts
  scripts/check-node-versions.js
  scripts/update-node.sh
  yarn.lock
Labels: auto-approve

#77 chore: set minNodeVersion to make node upgrade more consistent
  .github/workflows/build.yml
  .github/workflows/git-tags.yml
  .github/workflows/release.yml
  .github/workflows/upgrade-main.yml
  .github/workflows/upgrade-node.yml
  .projen/tasks.json
  .projenrc.ts
  package.json
  projenrc/update-tags.ts
  projenrc/upgrade-node.ts
  scripts/update-node.sh
Labels: automerge, auto-approve

#78 chore: increase Node.js version to 18
  .github/workflows/build.yml
  .github/workflows/release.yml
  .github/workflows/upgrade-main.yml
  .projen/deps.json
  .projenrc.ts
  README.md
  package.json
  yarn.lock
Labels: automated, automerge, security

#82 chore(deps): upgrade @hashicorp/js-releases to 1.7.0
  .projen/deps.json
  .projenrc.ts
  dist/index.js
  dist/index.js.map
  dist/licenses.txt
  package.json
  yarn.lock
Labels: auto-approve

#80 chore: automate upgrading the default CDKTF and Terraform versions
  .gitattributes
  .github/workflows/upgrade-cdktf.yml
  .github/workflows/upgrade-terraform.yml
  .gitignore
  .projen/files.json
  .projenrc.ts
  projenrc/upgrade-cdktf.ts
  projenrc/upgrade-terraform.ts
  scripts/check-terraform-version.js
  scripts/update-cdktf.sh
  scripts/update-terraform.sh
Labels: auto-approve
