Repository hashicorp/terraform-cdk-action, pull requests merged in 2024-08, with the labels that each got.

#201 chore(deps): upgrade dependencies
  dist/index.js
  dist/index.js.map
  yarn.lock
Labels: automerge, dependencies, auto-approve

#203 chore(deps): upgrade dependencies
  yarn.lock
Labels: automerge, dependencies, auto-approve

#202 fix: change default Terraform version to 1.9.4
  .projenrc.ts
  README.md
  action.yml
Labels: automerge, dependencies

#204 chore(deps): upgrade dependencies
  dist/index.js
  dist/index.js.map
  yarn.lock
Labels: automerge, dependencies, auto-approve

#206 chore(deps): upgrade dependencies
  dist/index.js
  dist/index.js.map
  yarn.lock
Labels: automerge, dependencies, auto-approve

#205 fix: change default Terraform version to 1.9.5
  .projenrc.ts
  README.md
  action.yml
Labels: automerge, dependencies

#208 chore(ci): fix syntax for concurrency in workflows
  .github/workflows/auto-approve.yml
  .github/workflows/automerge.yml
  .github/workflows/upgrade-cdktf.yml
  .github/workflows/upgrade-node.yml
  .github/workflows/upgrade-terraform.yml
  projenrc/auto-approve.ts
  projenrc/automerge.ts
  projenrc/upgrade-cdktf.ts
  projenrc/upgrade-node.ts
  projenrc/upgrade-terraform.ts
Labels: automerge, auto-approve

#209 chore(deps): update pinned versions of GitHub Actions
  .github/workflows/build.yml
  .github/workflows/release.yml
  .github/workflows/upgrade-cdktf.yml
  .github/workflows/upgrade-main.yml
  .github/workflows/upgrade-node-manually.yml
  .github/workflows/upgrade-node.yml
  .github/workflows/upgrade-terraform.yml
  .projenrc.ts
Labels: automerge, dependencies, auto-approve

#210 chore(ci): validate workflows as part of builds
  .projen/deps.json
  .projen/tasks.json
  package.json
  projenrc/index.ts
  yarn.lock
Labels: automerge, auto-approve

#211 chore(ci): upgrade projen-github-action-typescript
  .eslintrc.json
  .github/workflows/build.yml
  .github/workflows/pull-request-lint.yml
  .github/workflows/release.yml
  .github/workflows/upgrade-main.yml
  .gitignore
  .npmignore
  .projen/deps.json
  .projen/tasks.json
  dist/index.js
  dist/index.js.map
  dist/licenses.txt
  package.json
  projenrc/index.ts
  tsconfig.dev.json
  yarn.lock
Labels: automerge, dependencies, auto-approve
