Repository hashicorp/terraform-cdk-action, pull requests merged in 2025-01, with the labels that each got.

#242 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: automerge, dependencies, auto-approve

#239 fix: change default Terraform version to 1.10.3
  .projenrc.ts
  README.md
  action.yml
Labels: automerge, dependencies

#230 fix: change default CDKTF version to 0.20.11
  .projenrc.ts
  README.md
  action.yml
Labels: automerge, dependencies

#244 chore(deps): update pinned versions of GitHub Actions
  .github/workflows/auto-approve.yml
  .github/workflows/automerge.yml
  .github/workflows/build.yml
  .github/workflows/git-tags.yml
  .github/workflows/release.yml
  .github/workflows/upgrade-cdktf.yml
  .github/workflows/upgrade-main.yml
  .github/workflows/upgrade-node-manually.yml
  .github/workflows/upgrade-node.yml
  .github/workflows/upgrade-terraform.yml
  .projenrc.ts
Labels: automerge, auto-approve

#246 chore(ci): re-add the stale workflow to the codebase
  .gitattributes
  .github/workflows/stale.yml
  .gitignore
  .projen/files.json
  projenrc/index.ts
Labels: automerge, auto-approve

#248 chore(ci): auto-approve more workflows
  .github/workflows/upgrade-cdktf.yml
  .github/workflows/upgrade-terraform.yml
  projenrc/upgrade-cdktf.ts
  projenrc/upgrade-terraform.ts
Labels: automerge, auto-approve

#245 chore(ci): update required version of constructs when cdktf is upgraded
  .github/workflows/upgrade-cdktf.yml
  .projen/deps.json
  package.json
  projenrc/index.ts
  projenrc/upgrade-cdktf.ts
  scripts/update-cdktf.sh
  yarn.lock
Labels: automerge, auto-approve

#249 docs: create maintenance guide
  .github/MAINTENANCE.md
Labels: automerge, auto-approve

#250 fix: change default Terraform version to 1.10.4
  .projenrc.ts
  README.md
  action.yml
Labels: automerge, dependencies, auto-approve

#251 chore(deps): upgrade dependencies
  .projen/deps.json
  package.json
  yarn.lock
Labels: automerge, dependencies, auto-approve

#252 chore(ci): make workflows consistent across Projen projects
  .gitattributes
  .github/MAINTENANCE.md
  .github/workflows/auto-approve.yml
  .github/workflows/automerge.yml
  .github/workflows/upgrade-node-manually.yml
  .github/workflows/upgrade-node.yml
  .github/workflows/upgrade-terraform.yml
  .gitignore
  .projen/files.json
  projenrc/auto-approve.ts
  projenrc/automerge.ts
  projenrc/index.ts
  projenrc/lock-issues.ts
  projenrc/update-tags.ts
  projenrc/upgrade-cdktf.ts
  projenrc/upgrade-node.ts
  projenrc/upgrade-terraform.ts
  projenrc/util/random-cron.ts
  scripts/check-node-versions.js
  scripts/check-terraform-version.js
Labels: automerge, auto-approve

#253 chore(deps): upgrade dependencies
  dist/index.js
  dist/index.js.map
  dist/licenses.txt
  package.json
  yarn.lock
Labels: automerge, dependencies, auto-approve

#256 fix: change default Terraform version to 1.10.5
  .projenrc.ts
  README.md
  action.yml
Labels: automerge, dependencies, auto-approve

#257 chore(deps): upgrade dependencies
  yarn.lock
Labels: automerge, dependencies, auto-approve
